In [1]:
# Acedamic percentage in Operating Systems, percentage in Algorithms, Percentage in Programming Concepts, hackathons
# coding skills rating
# certifications
# Interested subjects
# interested career area 
# Suggested Job Role

In [2]:
import pandas as pd
import numpy as np
from sklearn import decomposition
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv("roo_data.csv")

In [4]:
data = dataset.iloc[:,:-1].values
label = dataset.iloc[:,-1].values
len(data[0])

38

In [6]:
dataset = dataset[['Acedamic percentage in Operating Systems','percentage in Algorithms','Percentage in Programming Concepts','hackathons','coding skills rating','certifications','Interested subjects','interested career area ','Suggested Job Role']]

In [7]:
dataset

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
...                                         ...                       ...   
19995                                        83                        67   
19996                                        80                        69   
19997                                        83                        70   
19998                                        68                        87   
19999                                        73                        77   

       Percentage in Programming Concepts  hackathons  coding skills rating  \
0                                      78           0                     4   
1                                      73           1                     2   
2                                      91           4                     1   
3                                      60           1                     2   
4                                      90           4                     6   
...                                   ...         ...                   ...   
19995                                  62           6                     1   
19996                                  83           0                     9   
19997                                  80           6                     2   
19998                                  91           4                     9   
19999                                  74           1                     7   

             certifications    Interested subjects   interested career area   \
0         shell programming        cloud computing          system developer   
1          machine learning               networks  Business process analyst   
2           app development                hacking                 developer   
3                    python               networks                   testing   
4           app development  Computer Architecture                   testing   
...                     ...                    ...                       ...   
19995       app development   Software Engineering          system developer   
19996            full stack             Management  Business process analyst   
19997  information security               networks           cloud computing   
19998            full stack                    IOT                   testing   
19999       app development                    IOT                   testing   

                              Suggested Job Role  
0                             Database Developer  
1                           Portal Administrator  
2                           Portal Administrator  
3                 Systems Security Administrator  
4                       Business Systems Analyst  
...                                          ...  
19995                         Technical Engineer  
19996                         E-Commerce Analyst  
19997              Business Intelligence Analyst  
19998  Software Quality Assurance (QA) / Testing  
19999                     Applications Developer  

[20000 rows x 9 columns]

In [8]:
data = dataset.iloc[:,:-1].values
label = dataset.iloc[:,-1].values
len(data[0])

8

In [10]:
dataset.iloc[:,5:9]

certifications    Interested subjects   interested career area   \
0         shell programming        cloud computing          system developer   
1          machine learning               networks  Business process analyst   
2           app development                hacking                 developer   
3                    python               networks                   testing   
4           app development  Computer Architecture                   testing   
...                     ...                    ...                       ...   
19995       app development   Software Engineering          system developer   
19996            full stack             Management  Business process analyst   
19997  information security               networks           cloud computing   
19998            full stack                    IOT                   testing   
19999       app development                    IOT                   testing   

                              Suggested Job Role  
0                             Database Developer  
1                           Portal Administrator  
2                           Portal Administrator  
3                 Systems Security Administrator  
4                       Business Systems Analyst  
...                                          ...  
19995                         Technical Engineer  
19996                         E-Commerce Analyst  
19997              Business Intelligence Analyst  
19998  Software Quality Assurance (QA) / Testing  
19999                     Applications Developer  

[20000 rows x 4 columns]

In [11]:
dataset.iloc[:,:5]

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
...                                         ...                       ...   
19995                                        83                        67   
19996                                        80                        69   
19997                                        83                        70   
19998                                        68                        87   
19999                                        73                        77   

       Percentage in Programming Concepts  hackathons  coding skills rating  
0                                      78           0                     4  
1                                      73           1                     2  
2                                      91           4                     1  
3                                      60           1                     2  
4                                      90           4                     6  
...                                   ...         ...                   ...  
19995                                  62           6                     1  
19996                                  83           0                     9  
19997                                  80           6                     2  
19998                                  91           4                     9  
19999                                  74           1                     7  

[20000 rows x 5 columns]

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()

In [14]:
for i in range(5,8):
    data[:,i] = labelencoder.fit_transform(data[:,i])
data[:5]

array([[69, 63, 78, 0, 4, 8, 4, 4],
       [78, 62, 73, 1, 2, 5, 7, 0],
       [71, 86, 91, 4, 1, 0, 6, 2],
       [76, 87, 60, 1, 2, 6, 7, 5],
       [92, 62, 90, 4, 6, 0, 0, 5]], dtype=object)

In [15]:
data[:5,5:]

array([[8, 4, 4],
       [5, 7, 0],
       [0, 6, 2],
       [6, 7, 5],
       [0, 0, 5]], dtype=object)

In [16]:
from sklearn.preprocessing import Normalizer

In [17]:
data1=data[:,:5]

In [18]:
normalized_data = Normalizer().fit_transform(data1)
print(normalized_data.shape)

(20000, 5)


In [19]:
normalized_data

array([[0.56660254, 0.51733275, 0.64050722, 0.        , 0.03284652],
       [0.63137718, 0.50186391, 0.59090428, 0.00809458, 0.01618916],
       [0.49306744, 0.59723662, 0.63195968, 0.02777845, 0.00694461],
       ...,
       [0.61474736, 0.51846163, 0.59252757, 0.04443957, 0.01481319],
       [0.47411229, 0.60658484, 0.6344738 , 0.02788896, 0.06275016],
       [0.56347561, 0.59435099, 0.57119446, 0.00771884, 0.05403191]])

In [20]:
data2=data[:,5:]
data2.shape

(20000, 3)

In [21]:
df1 = np.append(normalized_data,data2,axis=1)

df1.shape

(20000, 8)

In [22]:
X1 = pd.DataFrame(df1,columns=['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
       'Percentage in Programming Concepts',
       'hackathons', 'coding skills rating',
       'certifications',
       'Interested subjects', 'interested career area '])

In [23]:
X1.head()


Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                 0.566603                 0.517333   
1                                 0.631377                 0.501864   
2                                 0.493067                 0.597237   
3                                 0.583752                 0.668243   
4                                 0.643184                  0.43345   

  Percentage in Programming Concepts  hackathons coding skills rating  \
0                           0.640507           0            0.0328465   
1                           0.590904  0.00809458            0.0161892   
2                            0.63196   0.0277784           0.00694461   
3                           0.460857  0.00768095            0.0153619   
4                           0.629201   0.0279645            0.0419468   

  certifications Interested subjects interested career area   
0              8                   4                       4  
1              5                   7                       0  
2              0                   6                       2  
3              6                   7                       5  
4              0                   0                       5

In [24]:
label = labelencoder.fit_transform(label)
print(len(label))

20000


In [25]:
y=pd.DataFrame(label,columns=["Suggested Job Role"])
y.head()

Suggested Job Role
0                   7
1                  18
2                  18
3                  28
4                   2

In [26]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score

In [27]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.2,random_state=10) 


In [28]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [29]:

from sklearn.metrics import confusion_matrix,accuracy_score

In [30]:

y_pred = clf.predict(X_test)

In [31]:
y_pred


array([ 6, 27, 23, ..., 19, 24, 14])

In [32]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

In [33]:
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy*100)

confusion matrics= [[7 2 2 ... 5 2 3]
 [5 1 3 ... 3 3 2]
 [5 1 2 ... 5 1 3]
 ...
 [4 1 2 ... 4 1 5]
 [1 5 5 ... 1 3 2]
 [4 2 3 ... 5 6 3]]
  
accuracy= 3.1


# Decision Tree with Entropy

In [34]:
clf_entropy = tree.DecisionTreeClassifier(criterion = "entropy", random_state = 10)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=10)

In [35]:
entropy_y_pred=clf_entropy.predict(X_test)

In [36]:

cm_entopy = confusion_matrix(y_test,entropy_y_pred)

In [37]:
entropy_accuracy = accuracy_score(y_test,entropy_y_pred)

In [38]:
print("confusion matrics=",cm_entopy)
print("  ")
print("accuracy=",entropy_accuracy*100)

confusion matrics= [[3 4 3 ... 7 4 7]
 [3 2 1 ... 4 2 2]
 [2 3 4 ... 6 7 4]
 ...
 [9 4 2 ... 3 3 2]
 [1 6 1 ... 3 2 6]
 [4 2 2 ... 2 6 5]]
  
accuracy= 3.25


# SVM (Support vector machine) classifier

In [39]:
from sklearn import svm

In [40]:
clf = svm.SVC()
clf.fit(X_train, y_train)

C:\python\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC()

In [41]:
svm_y_pred = clf.predict(X_test)

In [42]:
svm_cm = confusion_matrix(y_test,svm_y_pred)
svm_accuracy = accuracy_score(y_test,svm_y_pred)

In [43]:
print("confusion matrics=",svm_cm)
print("  ")
print("accuracy=",svm_accuracy*100)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  
accuracy= 5.6000000000000005


# Changing data type

In [44]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.3,random_state=10) 


In [45]:
X_train.shape

(14000, 8)

In [46]:
X_train=pd.to_numeric(X_train.values.flatten())

In [47]:
X_train=X_train.reshape((14000,8))

In [50]:
!pip install xgboost


In [52]:
from xgboost import XGBClassifier

In [53]:
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', ...)

In [54]:
xgb_y_pred = clf.predict(X_test)

In [55]:
xgb_cm = confusion_matrix(y_test,xgb_y_pred)
xgb_accuracy = accuracy_score(y_test,xgb_y_pred)

In [56]:
print("confusion matrics=",xgb_cm)
print("  ")
print("accuracy=",xgb_accuracy*100)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  
accuracy= 5.75


In [72]:
y['Suggested Job Role'].unique()

array([ 7, 18, 28,  2, 25,  1,  4, 14, 32, 21, 33, 11,  3, 31, 20, 13, 19,
        9, 26, 27, 16,  5, 22, 10, 30, 12,  8,  0,  6, 15, 23, 29, 17, 24])